DROP TABLE IF EXISTS int_hmda__loans_enhanced CASCADE;

CREATE TABLE int_hmda__loans_enhanced AS
SELECT *, 
CASE WHEN ltv_ratio IS NULL OR ltv_ratio = 'NA' OR ltv_ratio = '' THEN 'Unknown' WHEN ltv_ratio ~ '^[0-9.]+$' AND ltv_ratio::NUMERIC <= 80 THEN '0-80% (Low Risk)' WHEN ltv_ratio ~ '^[0-9.]+$' AND ltv_ratio::NUMERIC <= 90 THEN '81-90% (Moderate Risk)' WHEN ltv_ratio ~ '^[0-9.]+$' AND ltv_ratio::NUMERIC <= 95 THEN '91-95% (High Risk)' WHEN ltv_ratio ~ '^[0-9.]+$' AND ltv_ratio::NUMERIC <= 100 THEN '96-100% (Very High Risk)' WHEN ltv_ratio ~ '^[0-9.]+$' THEN 'Over 100% (Extreme Risk)' ELSE 'Unknown' END AS ltv_bucket,
CASE WHEN dti_ratio IS NULL OR dti_ratio = 'NA' OR dti_ratio = '' THEN 'Unknown' WHEN dti_ratio ~ '^[0-9.]+$' AND dti_ratio::NUMERIC <= 36 THEN '0-36% (Excellent)' WHEN dti_ratio ~ '^[0-9.]+$' AND dti_ratio::NUMERIC <= 43 THEN '37-43% (Good)' WHEN dti_ratio ~ '^[0-9.]+$' AND dti_ratio::NUMERIC <= 50 THEN '44-50% (Fair)' WHEN dti_ratio ~ '^[0-9.]+$' THEN 'Over 50% (High Risk)' ELSE 'Unknown' END AS dti_bucket,
CASE WHEN loan_amount IS NULL OR loan_amount = 'NA' OR loan_amount = '' THEN 'Unknown' WHEN loan_amount ~ '^[0-9.]+$' AND loan_amount::NUMERIC < 100000 THEN 'Under $100K' WHEN loan_amount ~ '^[0-9.]+$' AND loan_amount::NUMERIC < 250000 THEN '$100K-$250K' WHEN loan_amount ~ '^[0-9.]+$' AND loan_amount::NUMERIC < 500000 THEN '$250K-$500K' WHEN loan_amount ~ '^[0-9.]+$' AND loan_amount::NUMERIC < 1000000 THEN '$500K-$1M' WHEN loan_amount ~ '^[0-9.]+$' THEN 'Over $1M' ELSE 'Unknown' END AS loan_amount_bucket,
CASE WHEN interest_rate IS NULL OR interest_rate = 'NA' OR interest_rate = '' THEN 'Unknown' WHEN interest_rate ~ '^[0-9.]+$' AND interest_rate::NUMERIC < 3 THEN 'Under 3%' WHEN interest_rate ~ '^[0-9.]+$' AND interest_rate::NUMERIC < 4 THEN '3%-4%' WHEN interest_rate ~ '^[0-9.]+$' AND interest_rate::NUMERIC < 5 THEN '4%-5%' WHEN interest_rate ~ '^[0-9.]+$' AND interest_rate::NUMERIC < 6 THEN '5%-6%' WHEN interest_rate ~ '^[0-9.]+$' THEN '6% and Above' ELSE 'Unknown' END AS interest_rate_bucket,
CASE WHEN borrower_income IS NULL OR borrower_income = 'NA' OR borrower_income = '' THEN 'Unknown' WHEN borrower_income ~ '^[0-9.]+$' AND borrower_income::NUMERIC < 50000 THEN 'Under $50K' WHEN borrower_income ~ '^[0-9.]+$' AND borrower_income::NUMERIC < 100000 THEN '$50K-$100K' WHEN borrower_income ~ '^[0-9.]+$' AND borrower_income::NUMERIC < 150000 THEN '$100K-$150K' WHEN borrower_income ~ '^[0-9.]+$' AND borrower_income::NUMERIC < 200000 THEN '$150K-$200K' WHEN borrower_income ~ '^[0-9.]+$' THEN 'Over $200K' ELSE 'Unknown' END AS income_bucket,
CASE loan_status WHEN '1' THEN 'Loan Originated' WHEN '2' THEN 'Application Approved but Not Accepted' WHEN '3' THEN 'Application Denied' WHEN '4' THEN 'Application Withdrawn' WHEN '5' THEN 'File Closed for Incompleteness' WHEN '6' THEN 'Purchased Loan' WHEN '7' THEN 'Preapproval Request Denied' WHEN '8' THEN 'Preapproval Request Approved but Not Accepted' ELSE 'Unknown' END AS loan_status_description,
CASE WHEN loan_status IN ('1', '2', '6', '8') THEN TRUE WHEN loan_status IN ('3', '7') THEN FALSE ELSE NULL END AS is_approved,
CASE WHEN (ltv_ratio ~ '^[0-9.]+$' AND ltv_ratio::NUMERIC > 95) OR (dti_ratio ~ '^[0-9.]+$' AND dti_ratio::NUMERIC > 43) OR (interest_rate ~ '^[0-9.]+$' AND interest_rate::NUMERIC > 6) THEN TRUE ELSE FALSE END AS is_high_risk,
CASE loan_type WHEN '1' THEN 'Conventional' WHEN '2' THEN 'FHA' WHEN '3' THEN 'VA' WHEN '4' THEN 'RHS/FSA' ELSE 'Other' END AS loan_type_description,
CASE loan_purpose WHEN '1' THEN 'Home Purchase' WHEN '2' THEN 'Home Improvement' WHEN '31' THEN 'Refinancing' WHEN '32' THEN 'Cash-out Refinancing' WHEN '4' THEN 'Other Purpose' WHEN '5' THEN 'Not Applicable' ELSE 'Unknown' END AS loan_purpose_description,
CASE occupancy_type WHEN '1' THEN 'Primary Residence' WHEN '2' THEN 'Second Residence' WHEN '3' THEN 'Investment Property' ELSE 'Unknown' END AS occupancy_description,
CASE WHEN total_units ~ '^[0-9]+$' AND total_units::INTEGER = 1 THEN 'Single Family' WHEN total_units ~ '^[0-9]+$' AND total_units::INTEGER BETWEEN 2 AND 4 THEN 'Small Multifamily (2-4 units)' WHEN total_units ~ '^[0-9]+$' AND total_units::INTEGER > 4 THEN 'Large Multifamily (5+ units)' ELSE 'Unknown' END AS property_type,
CASE WHEN applicant_age_above_62 = 'Yes' OR co_applicant_age_above_62 = 'Yes' THEN TRUE ELSE FALSE END AS has_senior_borrower,
CASE WHEN tract_minority_pct ~ '^[0-9.]+$' AND tract_minority_pct::NUMERIC >= 50 THEN TRUE ELSE FALSE END AS is_minority_tract,
CASE WHEN tract_to_msa_income_pct ~ '^[0-9.]+$' AND tract_to_msa_income_pct::NUMERIC < 80 THEN TRUE ELSE FALSE END AS is_low_income_tract,
CASE WHEN multifamily_affordable_units IS NOT NULL AND multifamily_affordable_units != 'NA' AND multifamily_affordable_units != '' THEN TRUE ELSE FALSE END AS has_affordable_units
FROM stg_hmda__loans;

select * from int_hmda__loans_enhanced;