DROP TABLE IF EXISTS stg_hmda__loans CASCADE;

CREATE TABLE stg_hmda__loans AS
SELECT
    activity_year AS loan_year,
    lei AS legal_entity_identifier,
    derived_msa_md AS msa_code,
    state_code,
    county_code,
    census_tract,
    conforming_loan_limit AS conforming_status,
    derived_loan_product_type AS loan_product_type,
    derived_dwelling_category AS dwelling_category,
    derived_ethnicity AS borrower_ethnicity,
    derived_race AS borrower_race,
    derived_sex AS borrower_sex,
    action_taken AS loan_status,
    purchaser_type,
    preapproval AS preapproval_status,
    loan_type,
    loan_purpose,
    lien_status,
    reverse_mortgage AS is_reverse_mortgage,
    open_end_line_of_credit AS is_open_end_line,
    business_or_commercial_purpose AS is_business_purpose,
    loan_amount,
    loan_to_value_ratio AS ltv_ratio,
    interest_rate,
    rate_spread,
    hoepa_status,
    total_loan_costs,
    total_points_and_fees,
    origination_charges,
    discount_points,
    lender_credits,
    loan_term,
    prepayment_penalty_term,
    intro_rate_period,
    negative_amortization AS has_negative_amortization,
    interest_only_payment AS has_interest_only_payment,
    balloon_payment AS has_balloon_payment,
    other_nonamortizing_features AS has_other_nonamortizing,
    property_value,
    construction_method,
    occupancy_type,
    manufactured_home_secured_property_type,
    manufactured_home_land_property_interest,
    total_units,
    multifamily_affordable_units,
    income AS borrower_income,
    debt_to_income_ratio AS dti_ratio,
    applicant_credit_score_type,
    co_applicant_credit_score_type,
    applicant_ethnicity_1,
    applicant_ethnicity_2,
    applicant_ethnicity_3,
    applicant_ethnicity_4,
    applicant_ethnicity_5,
    co_applicant_ethnicity_1,
    co_applicant_ethnicity_2,
    co_applicant_ethnicity_3,
    co_applicant_ethnicity_4,
    co_applicant_ethnicity_5,
    applicant_ethnicity_observed,
    co_applicant_ethnicity_observed,
    applicant_race_1,
    applicant_race_2,
    applicant_race_3,
    applicant_race_4,
    applicant_race_5,
    co_applicant_race_1,
    co_applicant_race_2,
    co_applicant_race_3,
    co_applicant_race_4,
    co_applicant_race_5,
    applicant_race_observed,
    co_applicant_race_observed,
    applicant_sex,
    co_applicant_sex,
    applicant_sex_observed,
    co_applicant_sex_observed,
    applicant_age,
    co_applicant_age,
    applicant_age_above_62,
    co_applicant_age_above_62,
    submission_of_application,
    initially_payable_to_institution,
    aus_1,
    aus_2,
    aus_3,
    aus_4,
    aus_5,
    denial_reason_1,
    denial_reason_2,
    denial_reason_3,
    denial_reason_4,
    tract_population,
    tract_minority_population_percent AS tract_minority_pct,
    ffiec_msa_md_median_family_income AS msa_median_income,
    tract_to_msa_income_percentage AS tract_to_msa_income_pct,
    tract_owner_occupied_units,
    tract_one_to_four_family_homes AS tract_single_family_homes,
    tract_median_age_of_housing_units AS tract_median_housing_age
FROM mortgage_hmda;